print("nhap diem A: ")
x1 = float(input("nhap x1: "))
y1 = float(input("nhap y1: "))
z1 = float(input("nhap z1: "))
print("nhap diem B: ")
x2 = float(input("nhap x2: "))
y2 = float(input("nhap y2: "))
z2 = float(input("nhap z2: "))
print("nhap diem C: ")
x3 = float(input("nhap x3: "))
y3 = float(input("nhap y3: "))
z3 = float(input("nhap z3: "))
print("nhap diem A': ")
x4 = float(input("nhap x4: "))
y4 = float(input("nhap y4: "))
z4 = float(input("nhap z4: "))
do_dai_AB = (((x2 - x1)**2) + ((y2 - y1)**2) + ((z2 - z1)**2)) ** (1/2)
print(f"do dai cua AB là: {do_dai_AB}")
do_dai_BC = (((x3 - x2)**2) + ((y3 - y2)**2) + ((z3 - z2)**2)) ** (1/2)
print(f"do dai cua BC la: {do_dai_BC}")
do_dai_CA = (((x4 - x3)**2) + ((y4 - y3)**2) + ((z4 - z3)**2)) ** (1/2)
print(f"do dai cua CA là: {do_dai_CA}")
do_dai_AA = (((x1 - x4)**2) + ((y1 - y4)**2) + ((z1 - z4)**2)) ** (1/2)
print(f"do dai cua AA la: {do_dai_AA}")
if do_dai_AB == do_dai_BC == do_dai_CA == do_dai_AA:
    the_tich = (do_dai_AB)**3
    print(f"the tich hinh hop vuong la: {the_tich}")
else:
    print("day khong phai la hinh hop vuong")

