print("nhap phuong trinh 1: ")
a1 = float(input("nhap a1: "))
b1 = float(input("nhap b1: "))
c1 = float(input("nhap c1: "))
print("nhap phuong trinh 2:")
a2 = float(input("nhap a2: "))
b2 = float(input("nhap b2: "))
c2 = float(input("nhap c2: "))
